version: "3.2"
services:
  db:
    image: mysql:latest
    container_name: mysqlDb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD : 57575han
      MYSQL_DATABASE      : sample_hr_db
      MYSQL_USER          : user
      MYSQL_PASSWORD      : 1234